name = input('What is your name? ')
print('Nice to meet you ' + name + ', my name is Chatbot. ')
age = input('How old are you? ')
print('Wow, ' + age + ' years old! I was born today.')
feeling = input('How are you feeling today? ')
print('Glad to hear you are feeling ' + feeling.lower() + '. That is wonderful to hear!')
color = input('What is your favorite color? ')
print('I love ' + color + '. 'That's my favorite too!')